models.py
from app import db
from datetime import datetime
import re

from flask_security import UserMixin, RoleMixin

def slugify(s):
    pattern = r'[^\w+]'
    return re.sub(pattern, '-', s)

post_tags = db.Table('post_tags',
                     db.Column('post_id', db.Integer, db.ForeignKey('post.id')),
                     db.Column('tag_id', db.Integer, db.ForeignKey('tag.id'))
                     )

"""-----------------------------------------------------------"""

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(140))
    slug = db.Column(db.String(140), unique=True)
    body = db.Column(db.Text)
    created = db.Column(db.DateTime, default=datetime.now())

    def __init__(self, *args, **kwargs):
        super(Post, self).__init__(*args, **kwargs)
        self.generate_slug()

    tags = db.relationship('Tag', secondary=post_tags, backref=db.backref('posts', lazy='dynamic'))

    def generate_slug(self):
        if self.title:
            self.slug = slugify(self.title.lower())

    def __repr__(self):
        return f'{self.title}'

"""-----------------------------------------------------------"""

class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    slug = db.Column(db.String(100))

    def __init__(self, *args, **kwargs):
        super(Tag, self).__init__(*args, **kwargs)
        self.slug = slugify(self.name)

    def __repr__(self):
        return f'{self.name}'

#######  Flask Security  #######
"""-----------------------------------------------------------"""

roles_users = db.Table('roles_users',
                       db.Column('user_id', db.Integer(), db.ForeignKey('user.id')),
                       db.Column('role_id', db.Integer(), db.ForeignKey('role.id'))
                       )

class User(db.Model, UserMixin):
    id = db.Column(db.Integer(), primary_key=True)
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(255))
    active = db.Column(db.Boolean())
    roles = db.relationship('Role',
                            secondary=roles_users,
                            backref=db.backref('users', lazy='dynamic'))
"""-----------------------------------------------------------"""

class Role(db.Model, RoleMixin):
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(100), unique=True)
    description = db.Column(db.String(255))

creation/forms.py
from wtforms import Form, StringField, TextAreaField

class PostForm(Form):
    title = StringField('Title')
    body = TextAreaField('Body')

app.py
'''
Created on 16 февр. 2020 г.

@author: mcghost
'''
from flask import Flask
from config import Configuration
from flask_sqlalchemy import SQLAlchemy

from flask_migrate import Migrate, MigrateCommand
from flask_script import Manager

from flask_admin import Admin
from flask_admin import AdminIndexView
from flask_admin.contrib.sqla import ModelView
from flask_admin import expose

from flask_security import SQLAlchemyUserDatastore
from flask_security import Security
from flask_security import current_user

from flask import redirect, url_for, request


app = Flask(__name__)
app.config.from_object(Configuration)

db = SQLAlchemy(app)


migrate = Migrate(app, db)
manager = Manager(app)
manager.add_command('db', MigrateCommand)


### ADMIN ###
from models import *

class AdminView(ModelView):
    def is_accessible(self):
        return current_user.has_role('admin')

    def inaccesible_callback(self, name, **kwargs):
        return redirect( url_for('security.login', next=request.url ))




class HomeAdminView(AdminIndexView):
    @expose('/')
    def index(self):
        if not current_user.has_role('admin'):
            return redirect( url_for('security.login', next=request.url ))
        else:
            return self.render(self._template)



class BaseModelView(ModelView):
    def on_model_change(self, form, model, is_created):
        model.generate_slug()
        return super(BaseModelView, self).on_model_change(form, model, is_created)


class PostAdminView(AdminView, BaseModelView):
    form_columns = ['title', 'body', 'tags']

class TagAdminView(AdminView, BaseModelView):
    form_columns = ['name', 'posts']



admin = Admin(app=app, name='FlaskApp', url='/', index_view=HomeAdminView())
admin.add_view(PostAdminView(Post, db.session))
admin.add_view(TagAdminView(Tag, db.session))

### Flask-security ###

user_datastore = SQLAlchemyUserDatastore(db, User, Role)
security = Security(app, user_datastore)

creation/blueprint.py
from flask import Blueprint
from flask import render_template

from models import Post, Tag
from .forms import PostForm

from flask import request
from flask import redirect
from flask import url_for
from app import db

from assist import change_query

from flask_security import login_required

creation = Blueprint('creation', __name__, template_folder='templates')


@creation.route('/', methods=['POST', 'GET'])
@login_required
def create_post():
     
    if request.method == 'POST':       
        title = request.form['title']
        body = request.form['body']
        
        if title and body:           #если создать пустые посты, то slug=None
                 
            try:
                post = Post(title=title, body=body)
                db.session.add(post)
                db.session.commit()
            except:
                print('Something wrong')
             
            return redirect(url_for('posts.index'))
     
     
    form = PostForm()
    return render_template('creation/create_post.html', form=form)

main.py
'''
Created on 16 февр. 2020 г.

@author: mcghost
'''
from app import app
from app import db

from posts.blueprint import posts
from creation.blueprint import creation

import view


app.register_blueprint(posts, url_prefix='/blog')
app.register_blueprint(creation, url_prefix='/creation')

if __name__ == '__main__':
    app.run()

posts/blueprint.py
'''
Created on 16 февр. 2020 г.

@author: mcghost
'''
from flask import Blueprint
from flask import render_template

from models import Post, Tag
from creation.forms import PostForm

from flask import request
from flask import redirect
from flask import url_for
from app import db

from assist import change_query

from flask_security import login_required



posts = Blueprint('posts', __name__, template_folder='templates')


@posts.route('/<slug>/edit/', methods=['POST', 'GET'])
@login_required
def edit_post(slug):
    post = Post.query.filter(Post.slug==slug).first_or_404()

    if request.method == 'POST':
        form = PostForm(formdata=request.form, obj=post)
        form.populate_obj(post) #Документация  wtforms класс Form
        db.session.commit()

        return redirect(url_for('posts.post_detail', slug=post.slug))

    form = PostForm(obj=post)
    return render_template('posts/edit_post.html', post=post, form=form)


@posts.route('/')
def index():

    q = request.args.get('q')

    page = request.args.get('page')

    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    if q:
        posts = change_query(q)
    else:    
        posts = Post.query.order_by(Post.id.desc())  
    pages = posts.paginate(page, 5, False)
          
    return render_template('posts/index.html', pages=pages)


@posts.route('/<slug>')
def post_detail(slug):
    post = Post.query.filter(Post.slug==slug).first_or_404() # здесь можно добавить уникальность
    tags = post.tags
    return render_template('posts/post_detail.html', post=post, tags=tags)


@posts.route('/tag/<slug>')
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug==slug).first_or_404()
    posts = tag.posts.all()
    return render_template('/posts/tag_detail.html', tag=tag, posts=posts)

creation/templates/creation/create_post.html
{% extends 'base0.html' %}


{% block title %}
    Create new post
{% endblock %}


{% block content_title %}
    New post
{% endblock %}


{% block content %}

    <div class="col-md-6">
        <form action="{{ url_for('creation.create_post') }}" method="POST">

            {% for field in form: %}

                <div class="form-group">
                    {{ field.label(class='control-label') }}
                    {{ field(class='form-control') }}
                </div>

            {% endfor %}
            
            <button type="submit" class="btn btn-success">Create</button>

        </form>
    </div>

{% endblock %}

posts/templates/posts/edit_post.html
{% extends 'base0.html' %}


{% block title %}
    Edit post
{% endblock %}


{% block content_title %}
    Edit post
{% endblock %}


{% block content %}

    <div class="col-md-6">
        <form action="{{ url_for('posts.edit_post', slug=post.slug) }}" method="POST">

            {% for field in form: %}

                <div class="form-group">
                    {{ field.label(class='control-label') }}
                    {{ field(class='form-control') }}
                </div>

            {% endfor %}
            
            <button type="submit" class="btn btn-success">Update</button>

        </form>
    </div>

{% endblock %}

posts/templates/posts/index.html
{% extends 'base0.html' %}

{% block title %}
  Blueprint index page
{% endblock  %}


{% block search %}

<form class="form-inline my-2 my-lg-0" method="GET">

<input class="form-control mr-sm-2" type="search" placeholder="type to search" aria-label="Search" name="q" value="{{ request.args.get('q', '') }}">

<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
</form>

{% endblock %}


{% block content_title %}
    Posts
{% endblock  %}

{% block content %}

    {% for post in pages.items %}
        
        <p style="text-indent:70px">
            <a href=" {{ url_for('posts.post_detail', slug=post.slug) }} ">{{ post.title }}</a>
        </p>

    {% endfor %}

    <nav aria-label="Page navigation example">
      <ul class="pagination">
        <li {% if pages.page==1 %}
            class="page-item disabled"
            {% else %}
            class="page-item"
            {% endif %}>
          <a class="page-link" href="./?page={{ pages.prev_num }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
          
        {% for page in pages.iter_pages() %}
          
        <li {% if page == pages.page %} class="page-item active" 
            {% endif %} class="page-item"><a class="page-link" href="./?page={{ page }}">{{ page }}</a></li>
          
        {% endfor %}
        <li {% if pages.page==pages.pages %} class="page-item disabled"
            {% else %} class="page-item"
            {% endif %}>
          <a class="page-link" href="./?page={{ pages.next_num }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
      </ul>
    </nav>

 
{% endblock  %}

posts/templates/posts/post_detail.html
{% extends 'base0.html' %}

{% block title %}
    {{ post.title }}
{% endblock  %}


{% block content_title %}
    {{ post.title}}
{% endblock  %}


{% block content %}
    <div class="tags">
        {% for tag in tags: %}
            <p style="text-indent:20px">
            <a href="{{ url_for('posts.tag_detail', slug=tag.slug) }}"><span class="badge badge-primary">{{ tag.name }}</span></a>   
            </p>
        {% endfor %}
    </div>
    
    
    <p style="text-indent:50px">
        {{ post.body }}
    </p>
{% endblock  %}

posts/templates/posts/tag_detail.html
{% extends 'base0.html' %}

{% block title %}
    {{ tag.name }} posts
{% endblock %}

{% block content_title %}
    Posts for "{{ tag.name }}" tag:
{% endblock %}


{% block content %}

    {% for post in posts %}
        <p style="text-indent:50px">
            <a href="{{ url_for('posts.post_detail', slug=post.slug) }}">{{ post.title }}</a>
        </p>
    {% endfor %}

{% endblock %}

templates/base0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

    <title>

        {% block title %} 

        {% endblock %} | Flask app

    </title>
</head>
<body>   
  
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

    <a class="navbar-brand" href="{{ url_for('index')  }}">Main</a>
    
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
   
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href=" {{ url_for('posts.index')  }} ">Blog<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
            <li>
                {% if current_user.has_role('admin')%}
                <a class="nav-link" href="/admin">Admin</a>
                <a class="nav-link" href=" {{ url_for('creation.create_post') }} ">Create post</a>
                {% endif %}
            </li>
      </li>
    </ul>
    
      {% block search %}
        
      
      {% endblock %}
      
  </div>
</nav> 
    
    
 
      <h1 style="text-indent:50px">

        {% block content_title %}

        {% endblock %}

      </h1>
      <p style="text-indent:70px">
        
        {% block content %}

        {% endblock %}
        
      </p>
    
</body>
</html>

templates/index.html
{% extends 'base0.html' %}

{% block title %}
    Blueprint index page
{% endblock  %}

{% block content_title %}
<div class="offset-md-4">
    Main page
</div>
{% endblock  %}

{% block content %}
<div class="col-md-8 offset-md-2">
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</div>
 
{% endblock  %}

templates/security/_messages.html
{%- with messages = get_flashed_messages(with_categories=true) -%}
  {% if messages %}
    <div class="flashes">
    {% for category, message in messages %}
      <div class="alert alert-{{ category }}">{{ message }}</div>
    {% endfor %}
    </div>
  {% endif %}
{%- endwith %}

templates/security/login_user.html
{% extends 'base0.html' %}

{% block title %}
    Login
{% endblock %}

{% block content %}

    {% from "security/_macros.html" import render_field_with_errors, render_field %}
    <div class="col-md-4 offset-md-4">
    {% include "security/_messages.html" %}
        <h2>{{ _('Login') }}</h2>
    <form action="{{ url_for_security('login') }}" method="POST" name="login_user_form">
      {{ login_user_form.hidden_tag() }}
      {{ render_field_with_errors(login_user_form.email, class='form-control') }}
      {{ render_field_with_errors(login_user_form.password, class='form-control') }}
      {{ render_field_with_errors(login_user_form.remember) }}
      {{ render_field(login_user_form.next) }}
      {{ render_field(login_user_form.submit, class='btn btn-success') }}
    </form>
    </div>
    {% include "security/_menu.html" %}

{% endblock %}